name: flutter_perf_monitor
description: Real-time performance monitoring with FPS tracking and memory usage for Flutter applications
version: 0.2.0
homepage: https://github.com/Dhia-Bechattaoui/flutter_perf_monitor
repository: https://github.com/Dhia-Bechattaoui/flutter_perf_monitor
issue_tracker: https://github.com/Dhia-Bechattaoui/flutter_perf_monitor/issues
documentation: https://github.com/Dhia-Bechattaoui/flutter_perf_monitor#readme

funding:
  - https://github.com/sponsors/Dhia-Bechattaoui

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.dhia_bechattaoui.flutter_perf_monitor
        pluginClass: FlutterPerfMonitorPlugin
      ios:
        pluginClass: FlutterPerfMonitorPlugin
